### ISSUE TITLE
Describe the steps necessary for the CRC wiki

### ISSUE THREAD

**Issue by andrecastro0o** [TIBHannover/chameleon#2]
Next to the README.md add README-SFB.md

For each instance (1153, 1368) indicate what branch should be used for them.

Describe the steps necessary load the custom css for the SFB  wiki

as in 
> Create custom files to prevent merge conflicts or overwriting on updates
Page layout: Add a custom.xml file to /skins/chameleon/layouts (copy existing, e.g. "standard.xml") to modify  Components
Element style: Add a custom.scss file to /skins/chameleon/resources/styles to define new css
Adapt LocalSettings.php (activate the interpretation of your files) 

```php
# Layout:
$egChameleonLayoutFile = __DIR__ . '/skins/chameleon/layouts/custom.xml';
# Style:
$egChameleonExternalStyleModule =  __DIR__ . '/skins/chameleon/resources/styles/custom.scss';
# Disable cache in LocalSettings.php for development: 
$egScssCacheType = CACHE_NONE;
```

**Comment by pitrade** [comment]
done
